language: csharp
matrix:
  include:
    - os: linux
      dist: trusty
      mono: latest
      dotnet: 2.1.3
      sudo: required
      env: MONO_BASE_PATH=/usr/lib/mono/
    - os: osx
      osx_image: xcode9.2
      mono: latest
      dotnet: 2.1.3
      sudo: required
      env: MONO_BASE_PATH=/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/
before_install:
  - |
    DOTNET_INSTALL_DIR="$PWD/.dotnetsdk"
    curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version "1.1.9" --install-dir "$DOTNET_INSTALL_DIR" --no-path
    curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version "2.1.105" --install-dir "$DOTNET_INSTALL_DIR" --no-path
    export PATH="$DOTNET_INSTALL_DIR:$PATH"
script: dotnet test
notifications:
  email: false